# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
minecraft_version=26.3-rc-1
loader_version=0.19.5
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.160.3+26.3

mc_extra_supported=

# Mod Properties
	mod_version = 0.15.0+26.3
	maven_group = space.essem
	archives_base_name = image2map

# Dependencies
	mapcanvas_version=0.9.0+26.2
	sgui_version=2.2.0+26.3